version: "3.9"

services:
  client:
    restart: always
    command: ["server:8080", "5"]
    build:
      dockerfile: Dockerfile-client
    depends_on:
      - server
  server:
    restart: always
    command: ["quotes.txt", "5"]
    build:
      dockerfile: Dockerfile-server
